### ISSUE TITLE
Print speed for initial layers is too fast for certain quality profiles

### ISSUE THREAD

**Issue by jerryrobo3d** [Robo3D/Slicing-Profiles#25]
@AllenMcAfee  For low quality PLA profile, the first layer was really fast.  Initial layer setting is 51 mm/s.

**Comment by AllenMcAfee** [comment]
@jerryrobo3d I've addressed this in the robo_base definition by limiting first layer speed to 30mm/s as a default value.  We can slow this down further for specialty materials in the quality profiles for those materials.  Speed_layer_0 has been removed from all quality profiles as this time.
