### ISSUE TITLE
Draft Quality Settings Modified For Better Print Results

### ISSUE THREAD

**Issue by JasonBarretto** [Robo3D/Slicing-Profiles#27]
These are the settings I changed in  _"Cura for Robo 3.1.0 Alpha"_ for better results with draft quality. 

## **Quality**
Initial Layer Line Width:  _Old: 100%_ / **New: 150%**

- _(Helps with first layer adhesion when not using a raft.)_

## **Material**
Initial Printing Temperature: _Old: 190°C_ / **New: 185°C**
Final Printing Temperature: _Old: 190°C_ / **New: 180°C**
Retract at layer change: _Old: _no__ / **New: yes**
Standby Temperature: _Old: 150°C_ / **New: 165°C**
Retraction Distance: _Old: 8.0mm_/ **New: 2.5mm**
Nozzle Switch Retraction Distance: _Old: 5mm_ / **New: 20mm**

- _(Helps speed up tool change process/ retraction distance now gets filament out of heat zone to reduce oozed material from inactive nozzle)_

## **Speed**
Print Speed: _Old: 60mm/s_ / **New: 40mm/s**
Support Speed: _Old: 54mm/s_ / **New: 40mm/s**
Initial Layer Speed: _Old: 51mm/s_ / **New: 25mm/s**

- _(first layer was a bit too fast, helps first layer reliability.)_

## Dual Extrusion
Prime Tower Thickness: _Old: 4.347mm_ / **New: 1mm**
Wipe Inactive Nozzle On Prime Tower: _Old: no_ / **New: yes**

- _(speeds up print and uses less material for prime tower/ wipes oozed material off inactive nozzle.)_

**Comment by AllenMcAfee** [comment]
Rolled into Cura 3, except for Standby temp (now 150 for PLA), Print speed is 50, and initial layer speed is 15.
